version: '3.8'

volumes:
  SalesWebMvcDB:

networks:
  mysqlNET:
  saleswebmvcNET:

services:

  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - SalesWebMvcDB:/var/lib/mysql
    networks:
      - mysqlNET
    environment:
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=1234567
      - MYSQL_ROOT_PASSWORD=1234567
      - MYSQL_ROOT_HOST=% mysql:8.0=value
      - bind-address:0.0.0.0

  saleswebmvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saleswebmvc
    networks:
      - mysqlNET
      - saleswebmvcNET
    ports:
      - 5000:80
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql
